version: '3.6'
services:
  db:
    image: postgis/postgis:latest
    platform: "linux/amd64"
    restart: always
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
      POSTGRES_DB: local
    networks:
      - api_net
    command: postgres -N 500
    ports:
      - "5432:5432"
    volumes:
      - type: tmpfs
        target: /var/lib/postgresql/data

  localstack:
    image: localstack/localstack
    environment:
      SERVICES: "s3"
      HOSTNAME: localstack
    networks:
      - api_net
    ports:
      - 4566:4566
    volumes:
      - "./scripts/s3_bootstrap.sh:/etc/localstack/init/ready.d/s3_bootstrap.sh"

  redis:
    image: redis:7.4.1-alpine
    restart: always
    networks:
      - api_net
    ports:
      - '6379:6379'
    volumes:
      - cache:/data

networks:
  api_net:
    driver: bridge

volumes:
  cache:
    driver: local
